### PR TITLE
i've left some comments for you

### PR DESCRIPTION
**Pull request by romanh1303**
i've added some comments and useful links check them out

### CODE REVIEW

**Comment by kurkula** [comment]
tell me ho are you?)

**Comment by kurkula** [comment]
> i've added some comments and useful links check them out


tell me ho are you?)

**Comment by kurkula** [comment]
> does it matter? xD

just intresting) where u get this link or how u find whis)

**Comment by romanh1303** [comment]
Big brother is watching you.
fix the project.
if you'll have some questions, ask here

**Comment by kurkula** [comment]
> Big brother is watching you. fix the project. if you'll have some questions, ask here

:D
okay, i have a couple question for u, i ask u tomorrow)  because i not so long ago understand what it's POM and i want to learn how exactly i need create tests

**Pull request merged**
